src/instrumentation/fetch.ts, src/sdk.ts
This PR resolves #23 by updating the default value handling of `fetch.includeTraceContext`.
The value is now coalesced using `??` rather than `||` to preserve falsy values specified in the config. The fetch instrumentation proxy is also updated to detect the function variant and invoke it with the current outbound request.
I've tested the variations manually by modifying the Workers example with the various options.
=> fixed includeTraceParent resolving

src/instrumentation/fetch.ts
This PR resolves #25 by assigning the `faas.execution` attribute to the [CF-Ray header](https://developers.cloudflare.com/fundamentals/get-started/reference/http-request-headers/#cf-ray) in the fetch handler instrumentation for inbound HTTP requests.
Note that the header is not set by `wrangler dev`, so this will only take effect on deployed Workers and Durable Objects.
=> adding faas.execution attribute from cf-ray

README.md, src/instrumentation/fetch.ts, src/sdk.ts, src/types.ts
This PR resolves #26 by incorporating a new configuration segment for the `fetch` handler with an option for `acceptTraceContext`. This option will allow disabling the incoming distributed trace context propagation for all requests or for individual requests using a callback function.
I manually tested this using the Workers example with the various options and `ConsoleSpanExporter` for confirming the trace and parent span are set correctly.
=> adding acceptTraceContext option for fetch handler

package.json
After the changes, here is the output of `pnpm run build && npm x --package=@arethetypeswrong/cli -c "attw $(pnpm pack)"`:
|                   | "@microlabs/otel-cf-workers" |
|-------------------|-------------------------------|
| node10            | 🟢                            |
| node16 (from CJS) | 🟢 (CJS)                      |
| node16 (from ESM) | 🟢 (ESM)                      |
| bundler           | 🟢                            |
Closes #29.
=> Fix types exports

src/instrumentation/do-storage.ts
When calling `storage.list()` with no arguments, the instrumented `DurableObjectStorage` instance throws an error due to `attrs` being undefined. This PR modifies the attribute creation to create the object first, then merges incoming attributes if applicable.
closes #33
=> fix Durable Object storage.list with no args

package.json, pnpm-lock.yaml, src/instrumentation/kv.ts
Implements most of #37 - except for replacing `get` with `getWithMetadata` under the hood:
- `workers-types` has been updated
- `cacheStatus` is now reported from `getWithMetadata` and `list`
- `list_complete` was reporting cursor instead of the boolean
- prefix attributes with `kv.`
=> Prefix KV instrumentation attributes, add cacheStatus

src/instrumentation/common.ts, src/provider.ts, src/sdk.ts, src/tracer.ts, src/types.ts
This PR attempts to close https://github.com/evanderkoogh/otel-cf-workers/issues/42. Not sure if you want this upstream @evanderkoogh, but I wanted to prove to myself it could be done, so here it is! Some demo code:
```ts
import { instrument, ResolveConfigFn } from '@microlabs/otel-cf-workers'
import { trace, Span, Context } from '@opentelemetry/api'
import { ConsoleSpanExporter, ReadableSpan, SpanProcessor } from '@opentelemetry/sdk-trace-base'
class LoggingSpanProcessor implements SpanProcessor {
onStart(span: Span, _parentContext: Context): void {
console.log(`startspan:${span.spanContext().spanId}`)
}
onEnd(span: ReadableSpan): void {
console.log(`endspan:${span.spanContext().spanId}`)
}
forceFlush(): Promise<void> {
return Promise.resolve()
}
shutdown(): Promise<void> {
return …
```
=> Support multiple span processors

package.json, pnpm-lock.yaml
As noticed by @lboynton in #55, changesets/cli ended up as a dependency instead of a dev dependency when it was added before rc.10. This PR moves it to devDependencies.
Resolves #55
=> Move changesets/cli to devDependencies

README.md
Teams at Cloudflare keep adding new bindings faster than we can implement telemetry for them. I've updated the readme to at least have a checklist of where we're at after Birthday Week.
=> Update Readme bindings progress

src/span.ts
when providing a TimeInput that is , this
library crashes. However, it is a totally safe input and
it's easy to normalize: we just do nothing.
This is happening when using Effect.ts (https://effect.website)
with this library as an exporter.
=> [fix] support hrtime tuple as TimeInput instead of throwing

.changeset/new-gifts-repair.md, README.md, src/instrumentation/analytics-engine.ts, src/instrumentation/env.ts
This PR implements instrumentation for Analytics Engine datasets. Couple of questions:
- The current code records the number of indexes (which is limited to 1 by the runtime) and the first index. This index can be an arraybuffer, which isn't "portable" so right now I just call `.toString`. Any recommendatons for that, if nothing else we can use a `TextDecoder` to get some log-friendly text out of it.
- Please double-check the names of tracers, dbs, basically all string constants.
Also this PR needs some testing before I'm confident merging it.
=> Implement Analytics Engine instrumentation

package.json, src/instrumentation/scheduled.ts
I noticed span.end() was only being called in the case of failures so we where not getting any data for scheduled invocations.
I also bumped the dependencies oltp-http, exporter-base and transformer to 0.44.0 so the peer deps of `@opentelemetry/api` are in the correct version range and and I can install packages without peer dep warnings
=> Fix span.end() call for scheduled tracing

.github/workflows/release.yml
The release workflow is broke due to a deadlock caused by having two concurrency checks
=> fix: Remove top-level concurrency in release workflow

.changeset/big-news-lick.md, src/instrumentation/kv.ts
KVAttributes functions don't have access to other functions, so we needed to inline functionality from get(argArray)
Tested in a Worker that calls getWithMetadata and confirmed it no longer crashes
=> fix: Inline kv.getWithMetadata() attributes to prevent exception

.changeset/polite-days-rush.md, src/instrumentation/kv.ts
We currently set has_result to true because getWithMetadata always returns an object with value/metadata even if the key didn't exist.
This should still return true when the key has an empty value because `!!emptyString = true`
=> fix: Set has_result to false when there is no value returned in kv.getWithMetadata()

src/instrumentation/env.ts, src/instrumentation/service.ts
It seems, that there are still some imports left in code, that have no exact extensions. This is not supported by node module resolution process:
[Node API - file extensions](https://nodejs.org/api/esm.html#mandatory-file-extensions)
When running otel-cf-workers code not in the ***bundled*** form (together with worker code), particularly in ***unit tests***.
I think, that is exactly due to the previous point: running a Cloudflare worker (even locally) usually includes a bundling step, by esbuild. And, possibly, exactly the bundler solves all the problems with having incorrect import signatures.
But, when writing __unit-tests__ for the workers (if you do not use a bundle at all), that becomes a problem - and module resolutions fails with console errors (in my case, it is the **mocha** …
=> fix: extensionless js imports

.changeset/rude-bottles-jog.md, src/sdk.ts
When setting up a new worker today, I copied the otel config resolver from another project. Unfortunately, the secret containing the api key had a different name there than I intended having in the new worker.
ResolveConfigFn previously had `env: any`, which means ts didn't catch this error. It now accepts an optional type parameter which allows users to typecheck their config resolver function better.
=> Make ResolveConfigFn type generic

.changeset/cuddly-cars-give.md, src/sdk.ts
This PR adds the missing `telemetry.sdk.version` attribute which is required by the spec: https://opentelemetry.io/docs/specs/otel/semantic-conventions/
Importing it from package.json will make sure it's updated automatically, assuming the build command is run after the version in package.json is incremented by changesets.
=> Fix telemetry sdk attributes

.husky/pre-commit, package.json, pnpm-lock.yaml
Hi :wave:,
This PR bumps major in `husky` and `rimraf`.
Husky release notes: https://github.com/typicode/husky/releases/tag/v9.0.1
The second commit contains the migration of the only script used.
Rimraf release notes: https://github.com/isaacs/rimraf/blob/main/CHANGELOG.md
No changes needed, v5 breaking changes only affect js api.
While I was at it, I also bumped other dev dependencies to their latest, including workers-types, which will be useful for my follow-up PRs.
=> chore: Bump devDependencies

.changeset/polite-dots-scream.md, .changeset/polite-schools-sip.md, .changeset/tiny-buckets-behave.md, src/instrumentation/common.ts, src/instrumentation/do-storage.ts
Previously, DO instrumentation copied all options to `attributes`. This PR implements special support for most methods (`transaction` is the only currently existing method on `DurableObjectStorage` that isn't handled properly, as it has a rollback method we should ideally proxy/track).
I also fixed a bug in `put`, pretty sure that the "entries" overload would've caused an exception previously as the instrumentation wasn't prepared for it.
=> Add more DO storage instrumentation

.changeset/hot-dodos-burn.md, src/instrumentation/env.ts, src/instrumentation/fetch.ts, src/instrumentation/queue.ts, src/instrumentation/scheduled.ts, src/instrumentation/version.ts
=> Detect version metadata binding, add attributes

.changeset/tasty-ghosts-tickle.md, src/instrumentation/env.ts
Since the introduction of JSRPC bindings, the `versionAttributes` function was also picking those up as potential version metadata bindings. This implementation of the binding search should allow tag to be an empty string (which it is by default), so detection should also be more thorough.
=> Improve version metadata binding detection

.changeset/strange-moose-fetch.md, src/sdk.ts
Fixes #79 
I recently ran into a somewhat similar situation as @code-hex where instrumenting a fetch caused all sorts of issues. For some cases, an uninstrumented fetch may be the only solution, so here's a PR exposing it as part of our API.
=> Export unwrapped global fetch

.changeset/fluffy-wasps-laugh.md, src/instrumentation/env.ts
Ref #116 , #134 
When we added the fix for the JSRPC runtime change, we disabled their caller-side instrumentation completely. This PR adds back the same instrumentation that we had before. For anyone reading, we still need to figure out a non-breaking way to instrument RPC-style function calls without interfering with user code.
=> Add back service binding fetch instrumentation

.changeset/pretty-coins-promise.md, src/instrumentation/do.ts, src/instrumentation/service.ts
Some spans were missed during #131, so here's a followup that renames Durable Object fetch, client fetch and service bindings.
=> Rename service binding and client fetch spans

src/wrap.ts
Fixes #139.
This PR inspects the unwrapped value, and if it's constructor is of `RpcProperty`, it handles binding by returning a different function that calls the RPC property as if it was bound.
I checked, and this sort of introspection is not unlike what Cloudflare do in their own Miniflare project:
https://github.com/cloudflare/workers-sdk/blob/d0754780c6d9a12984f1e4ed9b4f0952ba6b0888/packages/miniflare/src/workers/core/proxy.worker.ts#L223
=> Avoid calling bind on instances of RpcProperty

src/wrap.ts
This crashes:
```ts
new Miniflare({
...,
bindings: {
SOMETHING: null
}
});
```
because `null` crashes in `isVersionMetadata`.
So I fixed it by checking for `null` in `isProxyable`.
=> fix: make null not proxyable

src/instrumentation/env.ts
I'm sorry, I didn't fully cover the issue from #147. There's another codepath that calls `isVersionMetadata`, and I fixed that function as well.
=> fix: null in isVersionMetadata

src/config.ts, src/instrumentation/fetch.ts, src/spanprocessor.ts, src/tracer.ts
Functions on objects where some functions were instrumented, but not others (for example the Durable Object hibernateable Websocket API), would throw an error when calling `fetch`.
This shouldn't happen anymore :)
Thanks @benstechlab for the help in getting this PR out.
=> Fix issue where calling `fetch` in functions that weren't just instrumented threw an error

README.md, src/sampling.ts
In the `isHeadSampled` function, the flag wasn't tested as a bit, but as a whole value
For now, since there is only one flag in TraceFlags, it works, but it won't in the future if a flag is added
=> fix: traceFlags test in isHeadSampled function

.changeset/yellow-lamps-sin.md, package.json, pnpm-lock.yaml, src/exporter.ts, src/instrumentation/fetch.ts, src/span.ts
Fixes #149 
This PR updates all open-telemetry dependencies to their latest versions and makes `@open-telemetry/api` a peer-dependency, which is needed, because if the instrumented application had another version installed, it API won't work.
The biggest challenge is that I am not entirely sure if the semantic conventions were updated in a way that is different than the version that we were using previously. That is something that we need to figure out to make a note of that in a migrating to 1.0 blurb.
=> Upgrade dependencies and make @open-telemetry/api a peer-dependency

src/exporter.ts
Regression introduced in commit https://github.com/evanderkoogh/otel-cf-workers/commit/bd0a46a69da163ded5a6412b5bc839db159dd8f9 after api change in https://github.com/open-telemetry/opentelemetry-js/pull/4220
Update of opentelemetry api replaced boolean parameter useHex with options object. Without this object, it defaults to parameters `{ useHex: false, useLongBits: true }` which cannot be ingested by otel collector.
Tested manually by comparing data sent to local instance.
=>  fix: otlp json encoding

package.json
add cs-version to build script b/c github action builds before it releases (currently version file is only generated in release step
Fixes #164 
* fix failed build
to test:
- `npm run clean`
- `npm run build`
- ✅
=> build build-dependent versions.json before build builds

.changeset/thirty-ties-float.md, README.md, package.json, src/instrumentation/email.ts, src/sdk.ts, src/types.ts, tsup.config.ts
Ain't much but it's honest work ;D
This PR adds support for `email` handlers in Cloudflare Workers:
```ts
export default {
async email(message, env, ctx) {
// this is running in a trace!
},
};
```
This PR _does not_ instrument `email.reply` etc. It's out of scope of this PR. It's only for creating a span/trace for receiving the emails.
=> feat: add support for email triggers

README.md
I noticed that D1 was already supported but the READme didn't reflect that, so I thought I'd just update it quick.
https://github.com/evanderkoogh/otel-cf-workers/blob/main/src/instrumentation/env.ts#L62 is where the handling for it starts I think
=> Update README.md to point out D1 is supported

package.json, pnpm-lock.yaml, src/exporter.ts, src/sdk.ts, src/span.ts, src/tracer.ts, test/instrumentation/do-storage.test.ts
This change upgrades all OTel dependencies to their latest versions, and implements the necessary to deal with the breaking changes.  
Please let me know if I should include a `changeset` file, or you would rather do that by yourself when releasing.
=> Latest OTel dependencies
